version: '3.7'

services:

  econnessione:
    build:
      context: .
      target: build
    # Because `base` is strictly a utility service that is not part of the
    # app's run time, its `scale` is set to zero so that it doesn't run when
    # `docker-compose up` is invoked.
    scale: 0
    # volumes:
    #   - node_modules:/app/node_modules

  db-test:
    image: postgres:12
    ports:
      - 9432:5432
    environment:
      POSTGRES_USER: econnessione
      POSTGRES_PASSWORD: econnessione-password
      POSTGRES_DB: econnessione-test
    volumes:
      - db-test-data:/var/lib/postgresql/data

  db:
    image: postgres:12
    ports:
      - 8432:5432
    environment:
      POSTGRES_USER: econnessione
      POSTGRES_PASSWORD: econnessione-password
      POSTGRES_DB: econnessione
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    container_name: econnessione-api
    image: econnessione_econnessione
    env_file:
      - .env.dev
    environment:
      DEBUG: "@eco*"
      DB_HOST: db
      DB_PORT: 8432
    links:
      - db
    ports:
      - 4010:4010
    volumes:
      - ./:/app/:delegated
      # - node_modules:/app/node_modules:delegated
    tty: true
    working_dir: /app/services/api
    command: yarn develop
    restart: always

  web:
    container_name: econnessione-web
    image: econnessione_econnessione
    env_file:
      - .env.local
    ports:
      - 4001:3000
    volumes_from:
      - api
    working_dir: /app/services/web
    command: yarn start
    tty: true
    links:
      - api
    restart: always

  admin-web:
    container_name: econnessione-admin-web
    image: econnessione_econnessione
    env_file:
      - .env.local
    ports:
      - 4000:3000
    volumes_from:
      - api
    working_dir: /app/services/admin-web
    command: yarn start
    tty: true
    links:
      - api
    restart: always

volumes:
  db-data:
  db-test-data:
  node_modules:
  api-node_modules:
  web-node_modules:
  admin-web-node_modules:
  api-space:
