backend:
  name: git-gateway

# when using the default proxy server port
local_backend: true

publish_mode: editorial_workflow

media_folder: static/img
public_folder: /img

collections:
  - name: "actors"
    label: "Actor"
    folder: "content/actors"
    create: true
    slug: "{{username}}"
    editor:
      preview: true
    fields:
      - { label: "Full Name", name: "fullName", widget: "string" }
      - { label: "Username", name: "username", widget: "string" }
      - { label: "Avatar", name: "avatar", widget: "image", required: false }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "groups"
    label: "Group"
    folder: "content/groups"
    create: true
    slug: "{{name}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Avatar", name: "avatar", widget: "image" }
      - {
          label: "Members",
          name: "members",
          widget: "relation",
          collection: "actors",
          searchFields: ["username"],
          valueField: "username",
          multiple: true,
          required: false
        }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "topics"
    label: "Topic"
    folder: "content/topics"
    create: true
    slug: "{{name}}"
    fields:
      - { label: "Label", name: "label", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
