name: Deploy Alpha

on:
  workflow_run:
    workflows:
      - tests-e2e
    types:
      - completed
    branches:
      - release/alpha

jobs:

  deploy-alpha:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install modules
        # if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn

      - name: Build Packages
        run: yarn build:packages

      - name: Build Admin Web
        run: yarn workspace admin-web build
        env:
          PUBLIC_URL: https://econnessione-alpha.fra1.digitaloceanspaces.com/admin/
          API_URL: https://alpha-api.econnessione.org/

      - name: Upload Admin Web build to DO Space
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ALPHA_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ALPHA_SECRET_ACCESS_KEY }}
        run: |
          aws s3 sync ./services/admin-web/build s3://econnessione-alpha/admin \
            --follow-symlinks \
            --delete \
            --endpoint https://fra1.digitaloceanspaces.com/ \
            --acl public-read

      - name: Build Web
        run: yarn workspace web build
        env:
          PUBLIC_URL: https://econnessione-alpha.fra1.digitaloceanspaces.com/web/
          API_URL: https://alpha-api.econnessione.org/

      - name: Upload Web build to DO Space
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ALPHA_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ALPHA_SECRET_ACCESS_KEY }}
        run: |
          aws s3 sync ./services/web/build s3://econnessione-alpha/web \
            --follow-symlinks \
            --delete \
            --endpoint https://fra1.digitaloceanspaces.com/ \
            --acl public-read